### ISSUE TITLE
Bug: Crashes on editing

### ISSUE THREAD

**Issue by pianoelle** [matthewdeanmartin/dedlin#1]
```
--- Current line is 4, 4 lines total ---
*l
1,4 LIST 
   1 : Dear Santa,

   2 : Please give me toys.

   3 : Thanks,

   4 : Pia

--- Current line is 5, 4 lines total ---
*4
4 EDIT 
[Control C], [Enter] to exit edit mode
   4 : Pia Noelle
Traceback (most recent call last):
  File "/home/pia/test_dedlin/venv/bin/dedlin", line 8, in <module>
    sys.exit(main())
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/__main__.py", line 29, in main
    _ = run(
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/main.py", line 261, in run
    dedlin.entry_point(file_name, macro_file_name)
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/main.py", line 164, in entry_point
    line_number = self.doc.edit(line_number)
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/document.py", line 189, in edit
    line_text = self.lines[line_number - 1]
IndexError: list index out of range
(venv) pia@pia-envy:~/test_dedlin$ 

```
Created document. Tried to edit and hit Enter key to exit edit mode and it crashed.

**Comment by pianoelle** [comment]
```
Editing /home/pia/test_dedlin/mylist.txt
 * l
   1 : Rat

   2 : rabbit

   3 : Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, 

   4 : Cat

   5 : cat

   6 : rat

   7 : Stand

   8 : Hats

--- Current line is 8, 8 lines total ---
 * edit 8
Unknown command, type HELP for help
--- Current line is 8, 8 lines total ---
 * 8
[Control C], [Enter] to exit edit mode
   8 : Hat and Edited
Traceback (most recent call last):
  File "/home/pia/test_dedlin/venv/bin/dedlin", line 8, in <module>
    sys.exit(main())
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/__main__.py", line 35, in main
    _ = run(
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/__main__.py", line 85, in run
    dedlin.entry_point(file_name, macro_file_name)
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/main.py", line 163, in entry_point
    line_number = self.doc.edit(line_number)
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dpcontracts.py", line 509, in inner
    result = f(*args, **kwargs)
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/document.py", line 206, in edit
    raise ValueError("Can't edit row that doesn't exist.")
ValueError: Can't edit row that doesn't exist.
(venv) pia@pia-envy:~/test_dedlin$ ^C
(venv) pia@pia-envy:~/test_dedlin$ 

```

Bug still present

**Comment by pianoelle** [comment]
```
Editing /home/pia/test_dedlin/testpart2.txt
 * 1i
Control C to exit insert mode
?   1 :  apples
?   2 :  milk
?   3 :                                                                                                                                                                                                     

Exiting insert mode

--- Current line is 2, 2 lines total ---
 * 1
[Control C], [Enter] to exit edit mode
   1 : red apples
   2 : milk
--- Current line is 1, 2 lines total ---
 * 2
[Control C], [Enter] to exit edit mode
   2 : soymilk
Traceback (most recent call last):
  File "/home/pia/test_dedlin/venv/bin/dedlin", line 8, in <module>
    sys.exit(main())
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/__main__.py", line 35, in main
    _ = run(
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/__main__.py", line 85, in run
    dedlin.entry_point(file_name, macro_file_name)
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/main.py", line 163, in entry_point
    line_number = self.doc.edit(line_number)
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dpcontracts.py", line 509, in inner
    result = f(*args, **kwargs)
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/document.py", line 206, in edit
    raise ValueError("Can't edit row that doesn't exist.")
ValueError: Can't edit row that doesn't exist.
(venv) pia@pia-envy:~/test_dedlin$ 

```
Crashes when attempting to edit last line of document.

**Comment by pianoelle** [comment]
```
--- Current line is 2, 4 lines total ---
 * l
   1 : hug

   2 : tree

   3 : bug

   4 : slug

--- Current line is 4, 4 lines total ---
 * 3
[Control C], [Enter] to exit edit mode
   3 : bug
   4 : slug

--- Current line is 4, 4 lines total ---
 * exit

```
Bug fixed. Test shows no crash when editing last line.
