### ISSUE TITLE
Page command bug

### ISSUE THREAD

**Issue by pianoelle** [matthewdeanmartin/dedlin#10]
First bug: set current line to 1, then page command. List started at #2 cat when it should be #1 cat.
Second bug: set current line to 0 and it crashed.

```
--- Current line is 5, 5 lines total ---
 * 1, 3 list
   1 : cat
   2 : dogs
   3 : rabbit
   4 : red
--- Current line is 5, 5 lines total ---
 * help display
Display Commands
[range] List - display lines, set current to end of range
[range] Page - repeat to flip through entire document
[range] Spell - show spelling mistakes
[range] Search "[text]" 
--- Current line is 5, 5 lines total ---
 * 1 current
--- Current line is 1, 5 lines total ---
 * page
   2 : cat
   3 : dogs
   4 : rabbit
   5 : red
   6 : purple
--- Current line is 5, 5 lines total ---
 * 0 current
Traceback (most recent call last):
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/__main__.py", line 117, in run
    dedlin.entry_point(file_name, macro_file_name)
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/main.py", line 109, in entry_point
    command = next(command_generator)
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/command_sources.py", line 48, in generate
    command = parse_command(
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/parsers.py", line 284, in parse_command
    candidate = parse_range_only(just_command, front_part, original_text, current_line, document_length, phrases)
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/parsers.py", line 147, in parse_range_only
    line_range = extract_one_range(range_text, current_line, document_length)
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/parsers.py", line 59, in extract_one_range
    candidate = LineRange(start=start, offset=0, repeat=1)
  File "<string>", line 6, in __init__
  File "pydantic/dataclasses.py", line 100, in pydantic.dataclasses._generate_pydantic_post_init._pydantic_post_init
pydantic.error_wrappers.ValidationError: 1 validation error for LineRange
start
  start must be one or more (type=value_error)

History saved to /home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/.dedlin_history/history31.ed
(venv) pia@pia-envy:~/test_dedlin$ 

```

**Comment by pianoelle** [comment]
First bug is fixed: set current line to 1, then page command. List starts correctly at 1: cat.

```
--- Current line is 5, 6 lines total ---
 * 1 current
--- Current line is 1, 6 lines total ---
 * p
   1 : cat
   2 : dog
   3 : horse
   4 : pig
   5 : snake
```

Second bug still crashes when (set current line to 0).

```
--- Current line is 6, 6 lines total ---
 * 0 current
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/main.py", line 307, in save_on_crash
    raise type
  File "pydantic/error_wrappers.py", line 53, in pydantic.error_wrappers.ValidationError.__init__
TypeError: __init__() takes exactly 3 positional arguments (1 given)

Original exception was:
Traceback (most recent call last):
  File "/home/pia/test_dedlin/venv/bin/dedlin", line 8, in <module>
    sys.exit(main())
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/__main__.py", line 42, in main
    _ = run(
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/__main__.py", line 125, in run
    dedlin.save_on_crash(the_exception, None, None)
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/main.py", line 307, in save_on_crash
    raise type
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/__main__.py", line 118, in run
    dedlin.entry_point(file_name, macro_file_name)
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/main.py", line 110, in entry_point
    command = next(command_generator)
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/command_sources.py", line 49, in generate
    command = parse_command(
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/parsers.py", line 285, in parse_command
    candidate = parse_range_only(just_command, front_part, original_text, current_line, document_length, phrases)
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/parsers.py", line 147, in parse_range_only
    line_range = extract_one_range(range_text, current_line, document_length)
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/parsers.py", line 59, in extract_one_range
    candidate = LineRange(start=start, offset=0, repeat=1)
  File "<string>", line 6, in __init__
  File "pydantic/dataclasses.py", line 100, in pydantic.dataclasses._generate_pydantic_post_init._pydantic_post_init
    # +-------+-------+-------+
pydantic.error_wrappers.ValidationError: 1 validation error for LineRange
start
  start must be one or more (type=value_error)
(venv) pia@pia-envy:~/test_dedlin$ ^C
(venv) pia@pia-envy:~/test_dedlin$ 

```
