### ISSUE TITLE
Crashes when (set current line to 0)

### ISSUE THREAD

**Issue by pianoelle** [matthewdeanmartin/dedlin#14]
Bug. Crashes when (set current line to 0).

```
--- Current line is 6, 6 lines total ---
 * 0 current
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/main.py", line 307, in save_on_crash
    raise type
  File "pydantic/error_wrappers.py", line 53, in pydantic.error_wrappers.ValidationError.__init__
TypeError: __init__() takes exactly 3 positional arguments (1 given)

Original exception was:
Traceback (most recent call last):
  File "/home/pia/test_dedlin/venv/bin/dedlin", line 8, in <module>
    sys.exit(main())
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/__main__.py", line 42, in main
    _ = run(
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/__main__.py", line 125, in run
    dedlin.save_on_crash(the_exception, None, None)
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/main.py", line 307, in save_on_crash
    raise type
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/__main__.py", line 118, in run
    dedlin.entry_point(file_name, macro_file_name)
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/main.py", line 110, in entry_point
    command = next(command_generator)
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/command_sources.py", line 49, in generate
    command = parse_command(
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/parsers.py", line 285, in parse_command
    candidate = parse_range_only(just_command, front_part, original_text, current_line, document_length, phrases)
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/parsers.py", line 147, in parse_range_only
    line_range = extract_one_range(range_text, current_line, document_length)
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/parsers.py", line 59, in extract_one_range
    candidate = LineRange(start=start, offset=0, repeat=1)
  File "<string>", line 6, in __init__
  File "pydantic/dataclasses.py", line 100, in pydantic.dataclasses._generate_pydantic_post_init._pydantic_post_init
    # +-------+-------+-------+
pydantic.error_wrappers.ValidationError: 1 validation error for LineRange
start
  start must be one or more (type=value_error)
(venv) pia@pia-envy:~/test_dedlin$ ^C
(venv) pia@pia-envy:~/test_dedlin$ 


```

**Comment by pianoelle** [comment]
Bug fixed. 0 current does not crash.

```
--- Current line is 9, 9 lines total ---
 * 2 current
--- Current line is 2, 9 lines total ---
 * p
   2 : flour
   3 : C
   4 : peaches
   5 : almonds
   6 : soymilk
--- Current line is 7, 9 lines total ---
 * p
   7 : bear
   8 : cat
   9 : dog
--- Current line is 9, 9 lines total ---
 * 0 current
--- Current line is 1, 9 lines total ---
```
