### ISSUE TITLE
startup fails on Windows 11

### ISSUE THREAD

**Issue by smichr** [matthewdeanmartin/dedlin#27]
```
C:\>python -m dedlin --help
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\dedlin\__main__.py", line 30, in <module>
    from __about__ import __version__
ModuleNotFoundError: No module named '__about__'
```
If I add in `__main__` the path to about (`dedlin.__about__`) then the script runs.

**Comment by matthewdeanmartin** [comment]
Fixed! Thanks for bug report!

https://pypi.org/project/dedlin/1.19.2/
