### ISSUE TITLE
Crashes if you run List (l), then insert first line (1i), but if you don't run List first it doesn't crash.

### ISSUE THREAD

**Issue by pianoelle** [matthewdeanmartin/dedlin#4]
```
Editing /home/pia/test_dedlin/testpart2.txt
 * l
--- Current line is 1, 0 lines total ---
 * 1i
Control C to exit insert mode
Traceback (most recent call last):
  File "/home/pia/test_dedlin/venv/bin/dedlin", line 8, in <module>
    sys.exit(main())
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/__main__.py", line 35, in main
    _ = run(
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/__main__.py", line 85, in run
    dedlin.entry_point(file_name, macro_file_name)
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/main.py", line 155, in entry_point
    self.doc.insert(line_number)
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dpcontracts.py", line 507, in inner
    raise PreconditionError(description)
dpcontracts.PreconditionError: Current line must be a valid line
(venv) pia@pia-envy:~/test_dedlin$ ^C
(venv) pia@pia-envy:~/test_dedlin$ ^C
(venv) pia@pia-envy:~/test_dedlin$ 

```
Crashes if you run List (l), then insert first line (1i), but if you don't run List first it doesn't crash.

**Comment by pianoelle** [comment]
```
Editing /home/pia/test_dedlin/testpart4.txt
 * l
--- Current line is 1, 0 lines total ---
 * 1i
Control C to exit insert mode
?   1 :  test
?   2 :  best
?   3 :  rest
?   4 :                                                                                                                                                                                                     

Exiting insert mode

```
Bug fixed. Tested again - does not crash if you run List (l) and then insert first line (1i).
