### ISSUE TITLE
Fails to capture line breaks for browse command - after browsing and saving file.

### ISSUE THREAD

**Issue by pianoelle** [matthewdeanmartin/dedlin#5]
```
 * history
1,1000 browse http://wikipedia.org
1 current
l
help all
history
--- Current line is 358, 358 lines total ---
 * e
(venv) pia@pia-envy:~/test_d Ð¢Ð°ÑÐ°ÑÑÐ° / TatarÃ§a à¸ à¸²à¸©à¸²à¹                                                                 inaÐ¡ÑÐ¿ÑÐºÐ¸ / Srpski Srpskohrvatski / Ð¡ÑÐ¿ÑÐºÐ¾Ñ ÑÐ²Ð°ÑÑÐºÐ¸ SuomiSvenska à®¤à®®à®¿à®´à¯ano ×¢××¨××ª á¥áÐ°ÐºÐµÐ´Ð¾Ð½ÑÐºÐ¸ Ù à¸à¸¢Ð¢Ð¾Ò·Ð¸ÐºÓ£ ØªÛØ±Ú©Ø¬Ù TÃ¼rkÃ§e Ð£ÐºÑÐ°ÑÐ½ÑÑÐºÐ° Ø§Ø±Ø¯Ù Tiáº¿ngViá»t VolapÃ¼k Winaray ç²µèª ä¸­æ___Search___ Read Wikipedia in your language  __##  1 000 000+  articles* Polski* Ø§ÙÄÐ ÑÑÑÐºÐ¸Ð¹ Simple English Sinugboanong Binisaya SlovenÄ
                                     
```
Fails to capture line breaks for browse command - after browsing and saving file.

**Comment by pianoelle** [comment]
Bugs still present...

 * 1,100 browse http://wikipedia.org
--- Current line is 0, 358 lines total ---
 * l
Traceback (most recent call last):
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/__main__.py", line 117, in run
    dedlin.entry_point(file_name, macro_file_name)
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/main.py", line 150, in entry_point
    for line, end in self.doc.list_doc(command.line_range):
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/icontract/_checkers.py", line 890, in wrapper
    _assert_invariant(contract=contract, instance=instance)
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/icontract/_checkers.py", line 411, in _assert_invariant
    raise _create_violation_error(contract=contract, resolved_kwargs={'self': instance})
icontract.errors.ViolationError: File /home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/document.py, line 36 in <module>:
Current line must be a valid line: 1 <= self.current_line <= len(self.lines) or self.current_line in (0, 1) and not self.lines:
len(self.lines) was 358
self was <dedlin.document.Document object at 0x7fc854e553f0>
self.current_line was 0
self.lines was ['![Wikipedia](portal/wikipedia.org/assets/img/Wikipedia-logo-v2.png)', '#  Wikipedia  **The Free Encyclopedia**', '**English** 6 458 000+ articles', '**æ\x97¥æ\x9c¬èª\x9e** 1 314 000+ è¨\x98äº\x8b', '**Ð Ñ\x83Ñ\x81Ñ\x81ÐºÐ¸Ð¹** 1 798 000+ Ñ\x81Ñ\x82Ð°Ñ\x82ÐµÐ¹', '**Deutsch** 2 667 000+ Artikel', '**EspaÃ±ol** 1 755 000+ artÃ\xadculos', '**FranÃ§ais** 2 400 000+ articles', '**Italiano** 1 742 000+ voci', '**ä¸\xadæ\x96\x87** 1 256 000+ æ\x9d¡ç\x9b® / æ¢\x9dç\x9b®', '**PortuguÃªs** 1 085 000+ artigos', '**Polski** 1 512 000+ haseÅ\x82', 'Search Wikipedia', 'Afrikaans Polski Ø§Ù\x84Ø¹Ø±Ø¨Ù\x8aØ© Asturianu AzÉ\x99rbaycanca Ð\x91Ñ\x8aÐ»Ð³Ð°Ñ\x80Ñ\x81ÐºÐ¸', 'BÃ¢n-lÃ¢m-gÃº / HÅ\x8d-lÃ³-oÄ\x93 à¦¬à¦¾à¦\x82à¦²à¦¾ Ð\x91ÐµÐ»Ð°Ñ\x80Ñ\x83Ñ\x81ÐºÐ°Ñ\x8f CatalÃ', 'Ä\x8ceÅ¡tina Cymraeg Dansk Deutsch Eesti Î\x95Î»Î»Î·Î½Î¹ÎºÎ¬ English EspaÃ±ol', 'Esperanto Euskara Ù\x81Ø§Ø±Ø³Û\x8c FranÃ§ais Galego í\x95\x9cêµ\xadì\x96´ Õ\x80Õ¡ÕµÕ¥Ö\x80Õ¥Õ¶', 'à¤¹à¤¿à¤¨à¥\x8dà¤¦à¥\x80 Hrvatski Bahasa Indonesia Italiano ×¢×\x91×¨×\x99×ª á\x83¥á\x83\x90á\x83', 'á\x83\x97á\x83£á\x83\x9aá\x83\x98 Latina LatvieÅ¡u LietuviÅ³ Magyar Ð\x9cÐ°ÐºÐµÐ´Ð¾Ð½Ñ\x81ÐºÐ¸ Ù ØµØ±Ù\x89', 'Bahasa Melayu Bahaso Minangkabau á\x80\x99á\x80¼á\x80\x94á\x80ºá\x80\x99á\x80¬á\x80\x98á\x80¬á\x80\x9eá\x80¬ Nederlands', 'æ\x97¥æ\x9c¬èª\x9e Norsk (bokmÃ¥l) Norsk (nynorsk) Ð\x9dÐ¾Ñ Ñ\x87Ð¸Ð¹Ð½ OÊ»zbekcha /', 'Ð\x8eÐ·Ð±ÐµÐºÑ\x87Ð° PortuguÃªs Ò\x9aÐ°Ð·Ð°Ò\x9bÑ\x88Ð° / QazaqÅ\x9fa / Ù\x82Ø§Ø²Ø§Ù\x82Ø´Ø§ RomÃ¢nÄ\x83', 'Ð Ñ\x83Ñ\x81Ñ\x81ÐºÐ¸Ð¹ Simple English Sinugboanong Binisaya SlovenÄ\x8dina SlovenÅ¡Ä\x8dina', 'Ð¡Ñ\x80Ð¿Ñ\x81ÐºÐ¸ / Srpski Srpskohrvatski / Ð¡Ñ\x80Ð¿Ñ\x81ÐºÐ¾Ñ Ñ\x80Ð²Ð°Ñ\x82Ñ\x81ÐºÐ¸ Suomi', 'Svenska à®¤à®®à®¿à®´à¯\x8d Ð¢Ð°Ñ\x82Ð°Ñ\x80Ñ\x87Ð° / TatarÃ§a à¸ à¸²à¸©à¸²à¹\x84à¸\x97à¸¢', 'Ð¢Ð¾Ò·Ð¸ÐºÓ£ ØªÛ\x86Ø±Ú©Ø¬Ù\x87 TÃ¼rkÃ§e Ð£ÐºÑ\x80Ð°Ñ\x97Ð½Ñ\x81Ñ\x8cÐºÐ° Ø§Ø±Ø¯Ù\x88 Tiáº¿ng', 'Viá»\x87t VolapÃ¼k Winaray ç²µèª\x9e ä¸\xadæ\x96\x87', '__', '_Search_', '__ Read Wikipedia in your language  __', '##  1 000 000+  articles', '* Polski', '* Ø§Ù\x84Ø¹Ø±Ø¨Ù\x8aØ©', '* Deutsch', '* English', '* EspaÃ±ol', '* FranÃ§ais', '* Italiano', '* Ù ØµØ±Ù\x89', '* Nederlands', '* æ\x97¥æ\x9c¬èª\x9e', '* PortuguÃªs', '* Ð Ñ\x83Ñ\x81Ñ\x81ÐºÐ¸Ð¹', '* Sinugboanong Binisaya', '* Svenska', '* Ð£ÐºÑ\x80Ð°Ñ\x97Ð½Ñ\x81Ñ\x8cÐºÐ°', '* Tiáº¿ng Viá»\x87t', '* Winaray', '* ä¸\xadæ\x96\x87', '##  100 000+  articles', ...]

History saved to /home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/.dedlin_history/history30.ed
(venv) pia@pia-envy:~/test_dedlin$

**Comment by pianoelle** [comment]
Bug fixed.

```
Editing /home/pia/test_dedlin/test.txt
 * 1,1000 browse http://wikipedia.org
--- Current line is 358, 364 lines total ---
 * l
   1 : ![Wikipedia](portal/wikipedia.org/assets/img/Wikipedia-logo-v2.png)
   2 : #  Wikipedia  **The Free Encyclopedia**
   3 : **English** 6 458 000+ articles
   4 : **æ¥æ¬èª**à¤¦à¥ Hrvatski Bahasa Indonesia Italiano ×¢××¨××ª á¥áÐ°ÐºÐµÐ´Ð¾Ð½ÑÐºÐ¸ Ù ØµØ±Ù
   20 : Bahasa Melayu Bahaso Minangkabau áá¼ááºáá¬á¬èª Norsk (bokmÃ¥linaorsk (nynorsk) ÐÐ¾Ñ ÑÐ¸Ð¹Ð½ OÊ»zbekcha /
   24 : Ð¡ÑÐ¿ÑÐºÐ¸ / Srpski  Ð¢Ð°ÑÐ°ÑÑÐ° / TatarÃ§a à¸ à¸²à¸©à¸²à¹ÐºÐ¸ Suomi
   25 : Svenska à®¤à®®à®¿à®´à¯English Sinugboanong Binisaya SlovenÄ    à¸à¸¢
   26 : Ð¢Ð¾Ò·Ð¸ÐºÓ£ ØªÛØ±Ú©Ø¬Ù TÃ¼rkÃ§e Ð£ÐºÑÐ°ÑÐ½ÑÑÐºÐ° Ø§Ø±Ø¯Ù Tiáº¿ng
   27 : Viá»t VolapÃ¼k Winaray ç²µèª ä¸­æ
   28 : __
   29 : _Search_
   30 : __ Read Wikipedia in your language  __
   31 : ##  1 000 000+  articles
   32 : * Polski

```
