### ISSUE TITLE
Bug found when deleting lines

### ISSUE THREAD

**Issue by pianoelle** [matthewdeanmartin/dedlin#6]
```
--- Current line is 0, 0 lines total ---
 * 1i
Control C to exit insert mode
?   1 :  cheese
?   2 :  bread
?   3 :  apples
?   4 :  cookies
?   5 :  milk
?   6 :                                                                                                                                                                                                     

Exiting insert mode

--- Current line is 5, 5 lines total ---
 * l
   1 : cheese

   2 : bread

   3 : apples

   4 : cookies

   5 : milk

--- Current line is 5, 5 lines total ---
 * 1, 3 delete
Traceback (most recent call last):
  File "/home/pia/test_dedlin/venv/bin/dedlin", line 8, in <module>
    sys.exit(main())
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/__main__.py", line 35, in main
    _ = run(
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/__main__.py", line 87, in run
    dedlin.entry_point(file_name, macro_file_name)
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dedlin/main.py", line 146, in entry_point
    self.doc.delete(command.line_range)
  File "/home/pia/test_dedlin/venv/lib/python3.10/site-packages/dpcontracts.py", line 513, in inner
    raise PostconditionError(description)
dpcontracts.PostconditionError: Current line must be a valid line
(venv) pia@pia-envy:~/test_dedlin$ 

```
Bug found when deleting lines. In this case, a list was created, then command to delete lines 1 and 3, resulting in crash.

**Comment by pianoelle** [comment]
Bug fixed. Code now works....

Editing /home/pia/test_dedlin/list.txt
 * 1i
Control C to exit insert mode
?   1 :  red
?   2 :  blue'
?   3 :  green
?   4 :  orange
?   5 :  yellow
?   6 :                                                                                                                                                                                                     

Exiting insert mode

--- Current line is 5, 5 lines total ---
 * 2, 4, delete
Range invalid:2, 4,
Command Commands.DELETE not implemented
--- Current line is 5, 5 lines total ---
 * 2, 4 delete
Deleted lines 2 to 4
--- Current line is 1, 2 lines total ---
 * l
   1 : red
   2 : yellow
--- Current line is 2, 2 lines total ---
